"""Keyboard controller using g810-led"""

import subprocess


class KeyboardController:
    """Control Logitech RGB keyboards"""

    def __init__(self, device_info):
        """Initialize keyboard controller

        Args:
            device_info (dict): Device information with vid, pid, name
        """
        self.device = device_info
        self.vid = device_info['vid']
        self.pid = device_info['pid']
        self.name = device_info['name']

        # Determine the correct command based on device
        # Most devices use g213-led or g810-led as symlinks
        self.command = self._get_command()

    def _get_command(self):
        """Get the appropriate g*-led command for this device"""
        # Map PIDs to commands
        pid_commands = {
            'c336': 'g213-led',  # G213
            'c330': 'g410-led',  # G410
            'c33a': 'g413-led',  # G413
            'c342': 'g512-led',  # G512
            'c33c': 'g513-led',  # G513
            'c333': 'g610-led',  # G610
            'c337': 'g810-led',  # G810
            'c32b': 'g910-led',  # G910
            'c339': 'gpro-led',  # G Pro
        }

        return pid_commands.get(self.pid, 'g810-led')

    def set_color(self, color):
        """Set solid color

        Args:
            color (str): Hex color code (RRGGBB)
        """
        try:
            subprocess.run(
                ['sudo', self.command, '-a', color],
                check=True,
                capture_output=True
            )
            return True
        except subprocess.CalledProcessError as e:
            print(f"Error setting color: {e}")
            return False

    def set_effect(self, effect, color=None, speed=None):
        """Set lighting effect

        Args:
            effect (str): Effect name (cycle, breathing, wave)
            color (str): Hex color code (optional)
            speed (str): Effect speed (optional)
        """
        if effect == 'cycle':
            speed = speed or '10s'
            cmd = ['sudo', self.command, '-fx', 'cycle', 'all', speed]
        elif effect == 'breathing':
            color = color or 'ff0000'
            speed = speed or '5s'
            cmd = ['sudo', self.command, '-fx', 'breathing', 'all', color, speed]
        elif effect == 'wave':
            speed = speed or '5s'
            cmd = ['sudo', self.command, '-fx', 'waves', 'all', speed]
        else:
            return False

        try:
            subprocess.run(cmd, check=True, capture_output=True)
            return True
        except subprocess.CalledProcessError as e:
            print(f"Error setting effect: {e}")
            return False

    def get_script_content(self, color, effect=None, speed=None):
        """Generate script content for systemd service

        Args:
            color (str): Hex color code
            effect (str): Effect name (optional)
            speed (str): Effect speed (optional)

        Returns:
            str: Shell script content
        """
        script = f"""#!/bin/bash
# Logitech {self.name} RGB Lighting Script
# Generated by LogiLight

# Wait for device to be ready
sleep 1

"""

        if effect:
            if effect == 'cycle':
                speed = speed or '10s'
                script += f"/usr/bin/{self.command} -fx cycle all {speed}\\n"
            elif effect == 'breathing':
                speed = speed or '5s'
                script += f"/usr/bin/{self.command} -fx breathing all {color} {speed}\\n"
            elif effect == 'wave':
                speed = speed or '5s'
                script += f"/usr/bin/{self.command} -fx waves all {speed}\\n"
        else:
            script += f"/usr/bin/{self.command} -a {color}\\n"

        script += "\\nexit 0\\n"
        return script
