"""Mouse controller using ratbagctl"""

import subprocess
import re


class MouseController:
    """Control Logitech RGB mice"""

    def __init__(self, device_info):
        """Initialize mouse controller

        Args:
            device_info (dict): Device information with vid, pid, name
        """
        self.device = device_info
        self.vid = device_info['vid']
        self.pid = device_info['pid']
        self.name = device_info['name']
        self.device_id = None

        # Get ratbagctl device ID
        self._get_device_id()

    def _get_device_id(self):
        """Get the ratbagctl device identifier"""
        try:
            result = subprocess.run(
                ['ratbagctl', 'list'],
                capture_output=True,
                text=True
            )

            # Parse output to find our device
            # Format: device-id:    Device Name
            for line in result.stdout.split('\\n'):
                if 'Logitech' in line or 'G203' in line or 'G102' in line:
                    match = re.search(r'^([a-z-]+):', line)
                    if match:
                        self.device_id = match.group(1)
                        break

        except subprocess.CalledProcessError:
            pass

    def set_color(self, color):
        """Set solid color

        Args:
            color (str): Hex color code (RRGGBB)
        """
        if not self.device_id:
            return False

        try:
            # Set color
            subprocess.run(
                ['ratbagctl', self.device_id, 'led', '0', 'set', 'color', color],
                check=True,
                capture_output=True
            )

            # Set mode to 'on' (solid)
            subprocess.run(
                ['ratbagctl', self.device_id, 'led', '0', 'set', 'mode', 'on'],
                check=True,
                capture_output=True
            )

            return True
        except subprocess.CalledProcessError as e:
            print(f"Error setting color: {e}")
            return False

    def set_effect(self, effect, color=None):
        """Set lighting effect

        Args:
            effect (str): Effect name (breathing, cycle)
            color (str): Hex color code (optional)
        """
        if not self.device_id:
            return False

        try:
            if color:
                subprocess.run(
                    ['ratbagctl', self.device_id, 'led', '0', 'set', 'color', color],
                    check=True,
                    capture_output=True
                )

            # Set effect mode
            subprocess.run(
                ['ratbagctl', self.device_id, 'led', '0', 'set', 'mode', effect],
                check=True,
                capture_output=True
            )

            return True
        except subprocess.CalledProcessError as e:
            print(f"Error setting effect: {e}")
            return False

    def get_script_content(self, color, effect=None):
        """Generate script content for systemd service

        Args:
            color (str): Hex color code
            effect (str): Effect name (optional)

        Returns:
            str: Shell script content
        """
        if not self.device_id:
            return ""

        script = f"""#!/bin/bash
# Logitech {self.name} RGB Lighting Script
# Generated by LogiLight

# Wait for ratbagd service to be ready
sleep 2

# Set LED color
/usr/bin/ratbagctl {self.device_id} led 0 set color {color}

# Set LED mode
"""

        mode = effect if effect else 'on'
        script += f"/usr/bin/ratbagctl {self.device_id} led 0 set mode {mode}\\n"
        script += "\\nexit 0\\n"

        return script
